#Configuracoes do Jogo
#Mon Jun 15 09:30:31 BRT 2026
brilho=50
shaderAtivo=false
tecla_DIARIO=74
tecla_DIREITA=68
tecla_ESQUERDA=65
tecla_FALAR=70
tecla_FECHAR=81
tecla_INTERAGIR=69
tecla_INVENTARIO=66
tecla_MENU=27
tecla_OBJETIVOS=77
volumeEfeitos=50
